import {IMAGE_CONTAINERS,IMAGE_DESTINATIONS,IMAGE_LOCATIONS,imageModifiers,imageReviewProblem,type ImageReview as Review,type ImageRow} from '../parsers/imageTable';
import {REGIONS,VOCABULARY} from '../rules/anatomy';
export default function ImageReview({review,onChange,onConfirm,confirmed}:{review:Review;onChange:(review:Review)=>void;onConfirm:()=>void;confirmed:boolean}) {
 const problem=imageReviewProblem(review.rows);
 function update(id:number,key:keyof ImageRow,value:string) {onChange({...review,rows:review.rows.map(row=>row.id===id?{...row,[key]:value,...(['region','location'].includes(key)?{modifiers:undefined}:{})}:row)});}
 function select(row:ImageRow,key:'region'|'location'|'container'|'destination',options:string[],label:string) {
  return <select aria-label={`${label} for image row ${row.id}`} value={row[key]} onChange={e=>update(row.id,key,e.target.value)}><option value="">Needs review</option>{(row[key]&&!options.includes(row[key])?[row[key],...options]:options).map(value=><option key={value} value={value}>{value}</option>)}</select>;
 }
 return <section aria-label="PNG extraction review"><h3>Review PNG extraction</h3>
  <p className="warning">OCR can miss or misread rows. Compare the retained rows below with the Study Team rows in your original image. Correct the fields and add any missed rows before confirming. Only approved labels are shown; unrecognized text is marked “Needs review”. The source image and raw OCR text are not displayed.</p>
  <p>{review.rows.length} rows to review. {review.excludedRows??0} NIH/non-Study-Team rows removed automatically. Only Study Team rows are retained; NIH surgical pathology is excluded. Recognized material modifiers are selected automatically.</p>
  <p className="hint">Only anatomy, Container and Going where? cells are read after the header check. Passes, fragments and protocol do not change the row count. PHI header detection is not a guarantee of image de-identification.</p>
  <div className="table-wrap"><table><thead><tr><th>Image row</th><th>Region</th><th>Anatomic Location</th><th>Material Modifiers</th><th>Container</th><th>Going where?</th><th>Result</th><th>Correct row count</th></tr></thead><tbody>{review.rows.map(row=><tr key={row.id}><td>{row.id}</td><td>{select(row,'region',REGIONS,'Region')}</td><td>{select(row,'location',IMAGE_LOCATIONS,'Location')}</td><td><fieldset><legend>Material modifiers for image row {row.id}</legend>{VOCABULARY.map(value=><label key={value}><input type="checkbox" checked={(imageModifiers(row)?.split('; ')??[]).includes(value)} onChange={e=>{const current=imageModifiers(row)?.split('; ')??[];const selected=e.target.checked?[...current,value]:current.filter(x=>x!==value);onChange({...review,rows:review.rows.map(r=>r.id===row.id?{...r,modifiers:selected}:r)});}}/>{value}</label>)}</fieldset></td><td>{select(row,'container',IMAGE_CONTAINERS,'Container')}</td><td>{select(row,'destination',IMAGE_DESTINATIONS,'Destination')}</td><td>{row.destination==='NIH surg path'?'Exclude':!row.container?'Needs review':row.container==='Study Team'?'Retain':'Exclude'}</td><td><button onClick={()=>onChange({...review,rows:review.rows.filter(r=>r.id!==row.id)})}>Remove image row {row.id}</button></td></tr>)}</tbody></table></div>
  <div className="actions"><button onClick={()=>onChange({...review,rows:[...review.rows,{id:Math.max(0,...review.rows.map(r=>r.id))+1,region:'',location:'',container:'',destination:''}]})}>Add missed specimen row</button><button className="primary" disabled={!!problem||confirmed} onClick={onConfirm}>I checked every image row — confirm extraction</button></div>
  {problem&&<p role="alert">{problem}</p>}{confirmed&&<p className="success">Extraction confirmed. Enter Subject ID and Date Drawn below, then review the BSI output.</p>}
 </section>;
}
